# This rule is not used by the project src itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the tables.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: src
    app.kubernetes.io/managed-by: kustomize
  name: icebergtable-editor-role
rules:
- apiGroups:
  - tables.example.com
  resources:
  - icebergtables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tables.example.com
  resources:
  - icebergtables/status
  verbs:
  - get
