---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tables.example.com
  resources:
  - icebergtables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tables.example.com
  resources:
  - icebergtables/finalizers
  verbs:
  - update
- apiGroups:
  - tables.example.com
  resources:
  - icebergtables/status
  verbs:
  - get
  - patch
  - update
