apiVersion: tables.example.com/v1alpha1
kind: IcebergTable
metadata:
  name: customer-transactions-2
spec:
  dataProduct: esg  # <-- Added new field
  catalog:
    name: polaris
    type: rest
    warehouse: abfs://datalake@storageaccount.dfs.core.windows.net/warehouse
  database: customer
  table: transactions-2
  schema:
    - name: id
      type: long
      required: true
    - name: amount
      type: double
      required: true
  partitionSpec:
    - name: date
      transform: day
  properties:
    write.format.default: parquet
  retentionPolicy:
    snapshotExpirationDays: 21
